"""Assemble the single hosted script and hash its source inputs. No Node/runtime I/O."""
import hashlib,json,pathlib
HERE=pathlib.Path(__file__).resolve().parent
REPO=HERE.parents[2]
schema_dir=REPO/'src/webparts/aiCoeFrontDoor/content/marketing/schemas'
schemas={p.name:json.loads(p.read_text()) for p in sorted(schema_dir.glob('*.json'))}
schema_text=json.dumps(schemas,ensure_ascii=False,separators=(',',':'))
(HERE/'parts/05_EmbeddedSchemas.cs').write_text('public partial class Script { static readonly JObject Schemas=Parse(@"'+schema_text.replace('"','""')+'"); }\n')
parts=sorted((HERE/'parts').glob('*.cs'))
text='// Generated by connector/build.py; edit authored parts.\n'+'\n'.join(p.read_text() for p in parts)
assert len(text.encode())<=1000000
(HERE/'Script.cs').write_text(text,encoding='utf-8',newline='\n')
(HERE/'Script.csx').write_bytes((HERE/'Script.cs').read_bytes())
(HERE/'local/ScriptDigest.g.cs').write_text('static class ScriptDigest { public const string Sha256 = "'+hashlib.sha256(text.encode()).hexdigest()+'"; }\n')
manifest={'scriptBytes':len(text.encode()),'sha256':hashlib.sha256(text.encode()).hexdigest(),'parts':{str(p.relative_to(HERE)):hashlib.sha256(p.read_bytes()).hexdigest() for p in parts},'boundary':'LOCAL_CSHARP73_SHIM_ONLY_NOT_HOSTED_QUALIFICATION'}
(HERE.parent/'evidence/helper/source-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
print(json.dumps(manifest,indent=2))
