define([], function() {
  return {
    "PropertyPaneDescription": "Configure how the AI CoE Front Door presents your organization.",
    "BrandingGroupName": "Branding",
    "OrganizationNameFieldLabel": "Organization name",
    "OrganizationNameFieldDescription": "Shown in the header, the hero badge and the summaries, for example Contoso. Leave blank for neutral wording.",
    "GovernanceReferenceFieldLabel": "Governance reference",
    "GovernanceReferenceFieldDescription": "Policy reference quoted on review requests, for example a policy name, version and date. Leave blank for the default wording.",
    "ReviewSystemNameFieldLabel": "Review system name",
    "ReviewSystemNameFieldDescription": "Name of the performance-review system quoted in tool guidance. Leave blank for the default wording.",
    "DraftingGroupName": "AI drafting",
    "DraftServiceUrlFieldLabel": "AI draft flow URL",
    "DraftServiceUrlFieldDescription": "HTTP trigger URL of the drafting flow. The flow must allow any user in the tenant, and the Microsoft Flow Service API permission must be approved. Leave blank to keep plain summaries.",
    "TelemetryGroupName": "Telemetry",
    "TelemetryProviderFieldLabel": "Usage metrics provider",
    "TelemetryProviderOptionClaude": "Claude (Anthropic API)",
    "TelemetryProviderOptionOpenAi": "OpenAI (as shipped in 1.0.0.7)",
    "TelemetryProviderOptionBoth": "Claude and OpenAI",
    "PageLayoutGroupName": "Page layout",
    "ViewFieldLabel": "Piece shown on this page",
    "ViewOptionLegacy": "Whole front door on one page (default)",
    "ViewOptionHome": "Home tiles",
    "ViewOptionIdea": "Explore an AI idea",
    "ViewOptionToolCheck": "Check a tool or task",
    "ViewOptionTeamUsage": "Register team AI use",
    "ViewOptionHelpTraining": "Get help or training",
    "ViewOptionFeedback": "Share feedback",
    "ViewOptionTelemetry": "AI operations snapshot",
    "ViewOptionAdmin": "Administrator dashboard",
    "ViewOptionPage": "Content page",
    "LayoutFieldLabel": "Layout",
    "LayoutOptionWide": "Wide (full page width)",
    "LayoutOptionNarrow": "Narrow (one column)",
    "ReturnUrlFieldLabel": "Return page",
    "ReturnUrlFieldDescription": "Where \"All topics\" and \"Front Door\" lead: a site path such as SitePages/Requests.aspx or a full URL. Blank returns to the site home.",
    "PageContentGroupName": "Page content",
    "PageKeyFieldLabel": "Page key",
    "PageKeyFieldDescription": "Which page of the content document this instance shows, for example startHere, learn, useAi, requests, prompts or status.",
    "ContentUrlFieldLabel": "Page document",
    "ContentUrlFieldDescription": "Site path or URL of the JSON document with the page content. Blank reads SiteAssets/ai-coe-pages.json.",
    "PageLinksGroupName": "Page links",
    "PageLinkFieldDescription": "Site path such as SitePages/Explore-an-AI-idea.aspx or a full URL. Blank hides the tile.",
    "PageIdeaFieldLabel": "Explore an AI idea page",
    "PageToolCheckFieldLabel": "Check a tool or task page",
    "PageTeamUsageFieldLabel": "Register team AI use page",
    "PageHelpTrainingFieldLabel": "Get help or training page",
    "PageFeedbackFieldLabel": "Share feedback page",
    "PageTelemetryFieldLabel": "AI operations snapshot page",
    "PageAdminFieldLabel": "Administrator dashboard page",
    "PagePolicyFieldLabel": "AI policy page"
  }
});
