declare interface IAiCoeFrontDoorWebPartStrings {
  PropertyPaneDescription: string;
  BrandingGroupName: string;
  OrganizationNameFieldLabel: string;
  OrganizationNameFieldDescription: string;
  GovernanceReferenceFieldLabel: string;
  GovernanceReferenceFieldDescription: string;
  ReviewSystemNameFieldLabel: string;
  ReviewSystemNameFieldDescription: string;
  RoleGroupsFieldLabel: string;
  RoleGroupsFieldDescription: string;
  PaletteOverridesFieldLabel: string;
  PaletteOverridesFieldDescription: string;
  DraftingGroupName: string;
  DraftServiceUrlFieldLabel: string;
  DraftServiceUrlFieldDescription: string;
  CaseAnalysisUrlFieldLabel: string;
  CaseAnalysisUrlFieldDescription: string;
  TelemetryGroupName: string;
  TelemetryProviderFieldLabel: string;
  TelemetryProviderOptionClaude: string;
  TelemetryProviderOptionOpenAi: string;
  TelemetryProviderOptionBoth: string;
  PageLayoutGroupName: string;
  ViewFieldLabel: string;
  ViewOptionLegacy: string;
  ViewOptionApp: string;
  ViewOptionHome: string;
  ViewOptionIdea: string;
  ViewOptionToolCheck: string;
  ViewOptionTeamUsage: string;
  ViewOptionHelpTraining: string;
  ViewOptionFeedback: string;
  ViewOptionTelemetry: string;
  ViewOptionAdmin: string;
  ViewOptionPage: string;
  ViewOptionOutcome: string;
  LayoutFieldLabel: string;
  LayoutOptionWide: string;
  LayoutOptionNarrow: string;
  ReturnUrlFieldLabel: string;
  ReturnUrlFieldDescription: string;
  PageContentGroupName: string;
  PageKeyFieldLabel: string;
  PageKeyFieldDescription: string;
  ContentUrlFieldLabel: string;
  ContentUrlFieldDescription: string;
  PageLinksGroupName: string;
  PageLinkFieldDescription: string;
  PageIdeaFieldLabel: string;
  PageToolCheckFieldLabel: string;
  PageTeamUsageFieldLabel: string;
  PageHelpTrainingFieldLabel: string;
  PageFeedbackFieldLabel: string;
  PageTelemetryFieldLabel: string;
  PageAdminFieldLabel: string;
  PagePolicyFieldLabel: string;
  PageOutcomeFieldLabel: string;
}

declare module 'AiCoeFrontDoorWebPartStrings' {
  const strings: IAiCoeFrontDoorWebPartStrings;
  export = strings;
}
