"""Build the OSS Claude Case Analysis solution ZIP (unmanaged; flow packaged Off).

    python source/package.py --site-url https://<tenant>.sharepoint.com/sites/<site>
        --allowed-users "<email>[;<email>...]" [--api-name shared_...] --out <zip path>

The ZIP is assembled member-for-member from the Save-validated OSS Claude Draft Integration
1.0.0.4 flow package (byte-identical copy in source/template/, structural template only):
[Content_Types].xml is copied unchanged; solution.xml and customizations.xml keep every element
and attribute of that Dataverse export except the solution identity, the workflow row and the
connection references; the workflow JSON is generated by flow.py. Member order, compression and
attributes follow the template and timestamps are fixed, so the same arguments always produce the
same bytes. Nothing is imported or activated and no credential is involved. Derived reference
files (schemas, synthetic request, canonical Claude request) are written next to the ZIP.
"""
from pathlib import Path
import argparse
import hashlib
import json
import re
import sys
import uuid
import zipfile
import xml.etree.ElementTree as ET
from xml.sax.saxutils import escape
import flow
import integration as contract

ROOT = Path(__file__).resolve().parent
DELIVERY = ROOT.parent
TEMPLATE = ROOT / "template" / "02_OSSCloudWaveClaudeDraftIntegration_1_0_0_4.zip"
TEMPLATE_SHA256 = "2c7416f0ff6aaa2df09ce17cd5a97d2640d5024915231c9f272ff7c6f9ca9aa5"
TEMPLATE_FLOW_ID = "d227a436-d15f-5533-92db-ff80887f0bd8"
TEMPLATE_WORKFLOW_MEMBER = "Workflows/ClaudeIntakeDraft-" + TEMPLATE_FLOW_ID.upper() + ".json"
TEMPLATE_MEMBERS = ["customizations.xml", "solution.xml", TEMPLATE_WORKFLOW_MEMBER, "[Content_Types].xml"]
TEMPLATE_FLOW_NAME = "OSS Demo - Claude Intake Draft"
TEMPLATE_FLOW_DESCRIPTION = "Returns an AI-generated draft for human review. Never submits a case or makes a governance decision."
TEMPLATE_SOLUTION_DESCRIPTION = ("Authenticated idea draft generation through the separate Anthropic Claude connector. "
                                 "No case submission, approval or telemetry changes.")

SOLUTION_NAME = "OSSCloudWaveClaudeCaseAnalysis"
VERSION = "1.0.0.0"
# The flow first shipped in 1.0.0.0; later solution versions keep that as the workflow's IntroducedVersion.
INTRODUCED_VERSION = "1.0.0.0"
SOLUTION_DISPLAY_NAME = "OSS CloudWave Claude Case Analysis"
SOLUTION_DESCRIPTION = ("Authenticated executive case analysis: reads open AI CoE cases (structured fields and titles only) "
                        "and returns a Claude draft for human review through the existing Claude connector. "
                        "No case is created, changed or decided.")
FLOW_NAME = "OSS Demo - Claude Case Analysis"
FLOW_DESCRIPTION = "Returns an AI-generated analysis of open AI CoE cases for human review. Never changes a case or makes a governance decision."
# Existing OSS Claude Intake Draft custom connector (solution OSSCloudWaveClaudeDraftConnector 1.0.0.1).
CONNECTOR_ID = "9d027c49-6154-5783-9503-a0e9f0458709"
SHAREPOINT_REFERENCE_DISPLAY_NAME = "OSS Case Analysis SharePoint"
CLAUDE_REFERENCE_DISPLAY_NAME = "OSS Claude Case Analysis Connection"
ZIP_NAME = SOLUTION_NAME + "_" + VERSION.replace(".", "_") + ".zip"
BUILD_DATE_TIME = (2026, 9, 25, 0, 0, 0)
PLACEHOLDER_MARKERS = ("fixture", "placeholder", "example", "contoso", "fabrikam", "yourtenant", "your-",
                       "changeme", "<", ">", "{", "}")
REFERENCE_FILES = ("request.schema.json", "analysis.schema.json", "response.schema.json",
                   "synthetic-request.json", "claude-request-body.json")
BOM = "\ufeff"


def flow_id(site_url):
    return str(uuid.uuid5(uuid.NAMESPACE_URL, site_url + "/claude-case-analysis/v1#flow"))


def workflow_member(identifier):
    return "Workflows/ClaudeCaseAnalysis-" + identifier.upper() + ".json"


def sha256(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def json_bytes(value):
    return (json.dumps(value, indent=2) + "\n").encode("utf-8")


def attr(value):
    return escape(value, {'"': "&quot;"})


def replace_once(text, old, new, label):
    if text.count(old) != 1:
        raise ValueError(f"{label}: expected exactly one occurrence of {old!r}")
    return text.replace(old, new)


def decode_xml(data):
    text = data.decode("utf-8")
    if not text.startswith(BOM):
        raise ValueError("Template XML lost its byte-order mark")
    return text[len(BOM):]


def encode_xml(text):
    ET.fromstring(text.encode("utf-8"))  # well-formed or fail the build
    return (BOM + text).encode("utf-8")


def parse_allowed_users(value):
    """The Allowed users value as the designer stores it: addresses joined by semicolons."""
    users = [item.strip() for item in re.split(r"[;,\s]+", value or "") if item.strip()]
    joined = ";".join(users)
    flow.check_allowed_users(joined)
    return joined


def refuse_placeholders(values):
    for label, value in values:
        lowered = value.lower()
        marker = next((m for m in PLACEHOLDER_MARKERS if m in lowered), None)
        if marker:
            raise ValueError(f"Fixture or placeholder {label} ({value!r}, contains {marker!r}) may not be used in a deliverable package")


def solution_xml(data, fixture):
    text = decode_xml(data)
    manifest_name = SOLUTION_DISPLAY_NAME if not fixture else "LOCAL FIXTURE ONLY - NOT FOR IMPORT"
    text = replace_once(text, "<UniqueName>OSSCloudWaveClaudeDraftIntegration</UniqueName>",
                        "<UniqueName>" + SOLUTION_NAME + "</UniqueName>", "solution.xml")
    text = replace_once(text, '<LocalizedName description="OSS CloudWave Claude Draft Integration" languagecode="1033" />',
                        '<LocalizedName description="' + attr(manifest_name) + '" languagecode="1033" />', "solution.xml")
    text = replace_once(text, '<Description description="' + attr(TEMPLATE_SOLUTION_DESCRIPTION) + '" languagecode="1033" />',
                        '<Description description="' + attr(SOLUTION_DESCRIPTION) + '" languagecode="1033" />', "solution.xml")
    text = replace_once(text, "<Version>1.0.0.4</Version>", "<Version>" + VERSION + "</Version>", "solution.xml")
    replace_once(text, "<Managed>0</Managed>", "<Managed>0</Managed>", "solution.xml")
    return text


def customizations_xml(data, identifier, api_name, flow_name):
    text = decode_xml(data)
    text = replace_once(
        text,
        '<Workflow WorkflowId="{' + TEMPLATE_FLOW_ID + '}" Name="' + attr(TEMPLATE_FLOW_NAME) + '" Description="' + attr(TEMPLATE_FLOW_DESCRIPTION) + '">',
        '<Workflow WorkflowId="{' + identifier + '}" Name="' + attr(flow_name) + '" Description="' + attr(FLOW_DESCRIPTION) + '">',
        "customizations.xml")
    text = replace_once(text, "<JsonFileName>/" + TEMPLATE_WORKFLOW_MEMBER + "</JsonFileName>",
                        "<JsonFileName>/" + workflow_member(identifier) + "</JsonFileName>", "customizations.xml")
    text = replace_once(text, "<IntroducedVersion>1.0.0.4</IntroducedVersion>",
                        "<IntroducedVersion>" + INTRODUCED_VERSION + "</IntroducedVersion>", "customizations.xml")
    text = replace_once(text, '<LocalizedName languagecode="1033" description="' + attr(TEMPLATE_FLOW_NAME) + '" />',
                        '<LocalizedName languagecode="1033" description="' + attr(flow_name) + '" />', "customizations.xml")
    text = replace_once(text, '<Description languagecode="1033" description="' + attr(TEMPLATE_FLOW_DESCRIPTION) + '" />',
                        '<Description languagecode="1033" description="' + attr(FLOW_DESCRIPTION) + '" />', "customizations.xml")
    # Packaged Off, exactly as the template: StateCode 0 (Draft) / StatusCode 1.
    replace_once(text, "<StateCode>0</StateCode>", "<StateCode>0</StateCode>", "customizations.xml")
    replace_once(text, "<StatusCode>1</StatusCode>", "<StatusCode>1</StatusCode>", "customizations.xml")
    references = "\n".join([
        "  <connectionreferences>",
        '    <connectionreference connectionreferencelogicalname="' + flow.SHAREPOINT_CONNECTION_REFERENCE + '">',
        "      <connectionreferencedisplayname>" + escape(SHAREPOINT_REFERENCE_DISPLAY_NAME) + "</connectionreferencedisplayname>",
        "      <connectorid>/providers/Microsoft.PowerApps/apis/" + flow.SHAREPOINT_API_NAME + "</connectorid>",
        "      <iscustomizable>1</iscustomizable>",
        "      <promptingbehavior>0</promptingbehavior>",
        "      <statecode>0</statecode>",
        "      <statuscode>1</statuscode>",
        "    </connectionreference>",
        '    <connectionreference connectionreferencelogicalname="' + flow.CLAUDE_CONNECTION_REFERENCE + '">',
        "      <connectionreferencedisplayname>" + escape(CLAUDE_REFERENCE_DISPLAY_NAME) + "</connectionreferencedisplayname>",
        "      <connectorid>/providers/Microsoft.PowerApps/apis/" + api_name + "</connectorid>",
        "      <customconnectorid>",
        "        <connectorid>" + CONNECTOR_ID + "</connectorid>",
        "      </customconnectorid>",
        "      <iscustomizable>1</iscustomizable>",
        "      <promptingbehavior>0</promptingbehavior>",
        "      <statecode>0</statecode>",
        "      <statuscode>1</statuscode>",
        "    </connectionreference>",
        "  </connectionreferences>",
    ])
    text, count = re.subn(r"  <connectionreferences>\n.*?\n  </connectionreferences>", lambda _: references, text, flags=re.S)
    if count != 1:
        raise ValueError("customizations.xml: expected exactly one connectionreferences block")
    return text


def reference_documents():
    return {
        "request.schema.json": contract.request_schema(),
        "analysis.schema.json": contract.analysis_schema(),
        "response.schema.json": contract.response_schema(),
        "synthetic-request.json": contract.example_request(),
        "claude-request-body.json": contract.provider_request(contract.example_request(), contract.example_rows(),
                                                              contract.EXAMPLE_AS_OF),
    }


def build(site_url, allowed_users, api_name, out, fixture=False):
    site_url = (site_url or "").strip()
    flow.check_site_url(site_url)
    allowed_user = parse_allowed_users(allowed_users)
    flow.check_api_name(api_name)
    if not fixture:
        refuse_placeholders((("site URL", site_url), ("allowed user", allowed_user), ("API name", api_name)))
    out = Path(out)
    if out.suffix.lower() != ".zip":
        raise ValueError("--out must be a .zip path")
    if sha256(TEMPLATE) != TEMPLATE_SHA256:
        raise ValueError("Template package differs from the Save-validated 1.0.0.4 flow package")
    identifier = flow_id(site_url)
    flow_name = FLOW_NAME if not fixture else "LOCAL FIXTURE ONLY - Claude Case Analysis"
    document = flow.definition(api_name, site_url, allowed_user)
    with zipfile.ZipFile(TEMPLATE) as source:
        infos = source.infolist()
        if [info.filename for info in infos] != TEMPLATE_MEMBERS:
            raise ValueError("Unexpected template members")
        members = {info.filename: source.read(info) for info in infos}
    solution = replace_once(solution_xml(members["solution.xml"], fixture),
                            '<RootComponent type="29" id="{' + TEMPLATE_FLOW_ID + '}" behavior="0" />',
                            '<RootComponent type="29" id="{' + identifier + '}" behavior="0" />', "solution.xml")
    generated = {
        "customizations.xml": ("customizations.xml", encode_xml(customizations_xml(members["customizations.xml"], identifier, api_name, flow_name))),
        "solution.xml": ("solution.xml", encode_xml(solution)),
        TEMPLATE_WORKFLOW_MEMBER: (workflow_member(identifier), json_bytes(document)),
        "[Content_Types].xml": ("[Content_Types].xml", members["[Content_Types].xml"]),
    }
    out.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as output:
        for info in infos:
            name, data = generated[info.filename]
            entry = zipfile.ZipInfo(name, date_time=BUILD_DATE_TIME)
            entry.compress_type = zipfile.ZIP_DEFLATED
            entry.external_attr = info.external_attr
            entry.create_system = info.create_system
            output.writestr(entry, data)
    with zipfile.ZipFile(out) as check:
        if check.testzip() is not None:
            raise ValueError("ZIP failed its CRC check")
        if json.loads(check.read(workflow_member(identifier)).decode("utf-8")) != document:
            raise ValueError("Workflow JSON did not round-trip")
    written = []
    if not fixture:
        for name, value in reference_documents().items():
            (out.parent / name).write_bytes(json_bytes(value))
            written.append(name)
    return {"zip": str(out), "sha256": sha256(out), "bytes": out.stat().st_size, "members": [generated[i.filename][0] for i in infos],
            "solution": SOLUTION_NAME, "version": VERSION, "flow_id": identifier, "flow_name": flow_name,
            "site_url": site_url, "allowed_user": allowed_user, "runtime_api_name": api_name,
            "connector_logical_name": flow.CONNECTOR_LOGICAL_NAME, "connector_id": CONNECTOR_ID,
            "connection_references": [flow.SHAREPOINT_CONNECTION_REFERENCE, flow.CLAUDE_CONNECTION_REFERENCE],
            "flow_packaged_off": True, "fixture_only": fixture, "reference_files": written}


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--site-url", required=True, help="Explicit https SharePoint site URL holding the 'AI CoE Use Cases' list")
    parser.add_argument("--allowed-users", required=True, help="Email addresses allowed to call the trigger, separated by semicolons")
    parser.add_argument("--api-name", default=flow.DEFAULT_CLAUDE_API_NAME,
                        help="Runtime API name of the existing Claude connector (default: %(default)s)")
    parser.add_argument("--out", required=True, type=Path, help="Output .zip path; reference files are written next to it")
    parser.add_argument("--fixture", action="store_true", help="Local test build: allows fixture values, marks the package NOT FOR IMPORT")
    args = parser.parse_args(argv)
    try:
        result = build(args.site_url, args.allowed_users, args.api_name, args.out, args.fixture)
    except ValueError as error:
        print("Refused: " + str(error), file=sys.stderr)
        return 2
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
